# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chinese Poetry
email: 
description: Translated by Steve Lipscombe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stevelipscom.be"
icon: /favicon.ico
mailchimp-list: //stevelipscom.us21.list-manage.com/subscribe/post?u=14c7cf6be4e922e6fa5658d82&amp;id=2da45d4c93&amp;f_id=0035d5e1f0  

feed_icon: /assets/images/icon-512.jpeg
permalink: /:categories/:title

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 3
paginate_path: "/page/:num/"

show_excerpts: true
excerpt_length: 0
hide_search: true
hide_credits: true

# poets and poems

cao-cao: /poets/cao-cao.md
behold-the-deep-blue-sea: /_posts/2023-1-21-behold-the-deep-blue-sea.md

li-bai: /poets/li-bai.md

meng-haoran: /poets/meng-haoran.md
spring-dawn: /_posts/2023-1-31-spring-dawn.md

su-shi: /poets/su-shi.md
contemplating-a-game-of-weiqi: /_posts/2023-1-15-contemplating-a-game-of-weiqi.md

wang-wei: /poets/wang-wei.md
deer-place: {{ site.baseurl }}/_posts/2023-1-9-deer-place.md
writing-on-a-happening: /_posts/2023-2-4-writing-on-a-happening.md

